name       : tcpdump
version    : 4.9.3
release    : 13
source     :
    - https://github.com/the-tcpdump-group/tcpdump/archive/tcpdump-4.9.3.tar.gz : 7f3b0c5f3832b32b15f3707a17eb441bfb3791d78550419e1c58ac3a10d696d9
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - pkgconfig(libpcap)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
