name       : tcpdump
version    : 4.8.1
release    : 6
source     :
    - http://www.tcpdump.org/release/tcpdump-4.8.1.tar.gz : 20e4341ec48fcf72abcae312ea913e6ba6b958617b2f3fb496d51f0ae88d831c
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - libpcap-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
