name       : tcpdump
version    : 4.9.1
release    : 8
source     :
    - http://www.tcpdump.org/release/tcpdump-4.9.1.tar.gz : f9448cf4deb2049acf713655c736342662e652ef40dbe0a8f6f8d5b9ce5bd8f3
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - libpcap-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
