name       : tcpdump
version    : 4.9.2
release    : 11
source     :
    - https://github.com/the-tcpdump-group/tcpdump/archive/tcpdump-4.9.2.tar.gz : 88a3489838004cd9f341826178a7eb7c406fa9b99a7a8b8ad03aed113542053a
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - libpcap-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
