name       : tcpdump
version    : 4.99.4
release    : 15
source     :
    - https://github.com/the-tcpdump-group/tcpdump/archive/tcpdump-4.99.4.tar.gz : c98e6b972b21f28050e10389dd87037ff17766967bea714e4c8b752c5e5c7098
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - pkgconfig(libpcap)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
