name        : tcpdump
version     : 4.7.4
release     : 5
source     :
    - http://www.tcpdump.org/release/tcpdump-4.7.4.tar.gz : 6be520269a89036f99c0b2126713a60965953eab921002b07608ccfc0c47d9af
license     :
    - BSD
summary     : dump traffic on a network
builddeps   :
    - libpcap-devel
    - openssl-devel
description : |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
