name       : tcpdump
version    : 4.9.0
release    : 7
source     :
    - git|git://anonscm.debian.org/users/rfrancoise/tcpdump.git : 79f48aeebd46efe58640500d49e338afddeff432
    - http://www.tcpdump.org/release/tcpdump-4.8.1.tar.gz : 20e4341ec48fcf72abcae312ea913e6ba6b958617b2f3fb496d51f0ae88d831c
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - libpcap-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
