name       : tcpdump
version    : 4.9.2
release    : 9
source     :
    - http://www.tcpdump.org/release/tcpdump-4.9.2.tar.gz : 798b3536a29832ce0cbb07fafb1ce5097c95e308a6f592d14052e1ef1505fe79
license    : BSD-2-Clause
component  : network.util
summary    : Dump traffic on a network
description: |
    Tcpdump prints out a description of the contents of packets on a network interfacethat matches a given expression, allowing targeted analysis. It can save data to files for analysis later as well.
builddeps  :
    - libpcap-devel
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
